name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "464e889a-93a3-40d7-aca6-189ff477518e" \
            --password "Pw_8Q~XCqRgqVG24QSPcJ8HE5ptrIi18Cs07abiP" \
            --tenant "f63c0b81-f86b-4b01-9374-66bb63691322"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "b0ec999f-b48b-4499-8f02-dcd3bf1dbe7b"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "464e889a-93a3-40d7-aca6-189ff477518e" \
            --password "Pw_8Q~XCqRgqVG24QSPcJ8HE5ptrIi18Cs07abiP" \
            --tenant "f63c0b81-f86b-4b01-9374-66bb63691322"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "b0ec999f-b48b-4499-8f02-dcd3bf1dbe7b"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
